INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(1, 3, 1);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(1, 3, 2);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(1, 3, 3);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(1, 3, 4);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(1, 3, 5);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(1, 3, 1196);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(2, 3, 6);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(2, 3, 7);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(2, 3, 8);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(2, 3, 9);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(2, 3, 10);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(2, 3, 1197);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(3, 3, 11);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(3, 3, 12);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(3, 3, 13);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(3, 3, 14);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(3, 3, 15);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(3, 3, 1198);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(4, 3, 16);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(4, 3, 17);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(4, 3, 18);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(4, 3, 19);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(4, 3, 20);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(4, 3, 1199);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(5, 3, 21);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(5, 3, 22);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(5, 3, 23);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(5, 3, 24);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(5, 3, 25);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(5, 3, 1200);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(6, 3, 26);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(6, 3, 27);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(6, 3, 28);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(6, 3, 29);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(6, 3, 30);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(6, 3, 1201);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(47, 3, 402);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(47, 3, 403);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(47, 3, 404);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(47, 3, 405);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(47, 3, 406);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(47, 3, 1245);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(48, 3, 360);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(48, 3, 361);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(48, 3, 362);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(48, 3, 363);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(48, 3, 364);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(48, 3, 1238);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(49, 3, 370);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(49, 3, 371);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(49, 3, 372);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(49, 3, 373);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(49, 3, 374);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(49, 3, 1240);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(89, 3, 1285);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(89, 3, 1286);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(89, 3, 1287);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(89, 3, 1288);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(89, 3, 1289);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(89, 3, 1290);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(90, 3, 1291);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(90, 3, 1292);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(90, 3, 1293);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(90, 3, 1294);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(90, 3, 1295);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(90, 3, 1296);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(7, 3, 31);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(7, 3, 32);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(7, 3, 33);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(7, 3, 34);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(7, 3, 35);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(7, 3, 1202);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(60, 3, 412);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(60, 3, 413);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(60, 3, 414);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(60, 3, 415);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(60, 3, 416);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(60, 3, 1247);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(93, 3, 1313);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(94, 3, 1319);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(8, 3, 36);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(8, 3, 37);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(8, 3, 38);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(8, 3, 39);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(8, 3, 40);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(8, 3, 1203);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(15, 3, 71);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(15, 3, 72);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(15, 3, 73);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(15, 3, 74);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(15, 3, 75);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(15, 3, 1210);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(53, 3, 392);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(53, 3, 393);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(53, 3, 394);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(53, 3, 395);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(53, 3, 396);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(53, 3, 1243);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(9, 3, 41);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(9, 3, 42);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(9, 3, 43);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(9, 3, 44);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(9, 3, 45);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(9, 3, 1204);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(10, 3, 46);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(10, 3, 47);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(10, 3, 48);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(10, 3, 49);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(10, 3, 50);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(10, 3, 1205);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(11, 3, 51);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(11, 3, 52);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(11, 3, 53);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(11, 3, 54);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(11, 3, 55);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(11, 3, 1206);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(12, 3, 56);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(12, 3, 57);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(12, 3, 58);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(12, 3, 59);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(12, 3, 60);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(12, 3, 1207);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(13, 3, 61);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(13, 3, 62);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(13, 3, 63);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(13, 3, 64);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(13, 3, 65);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(13, 3, 1208);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(14, 3, 66);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(14, 3, 67);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(14, 3, 68);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(14, 3, 69);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(14, 3, 70);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(14, 3, 1209);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(50, 3, 365);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(50, 3, 366);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(50, 3, 367);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(50, 3, 368);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(50, 3, 369);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(50, 3, 1239);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(51, 3, 382);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(51, 3, 383);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(51, 3, 384);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(51, 3, 385);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(51, 3, 386);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(51, 3, 1241);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(52, 3, 387);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(52, 3, 388);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(52, 3, 389);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(52, 3, 390);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(52, 3, 391);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(52, 3, 1242);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(87, 3, 1191);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(87, 3, 1192);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(87, 3, 1193);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(87, 3, 1194);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(87, 3, 1195);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(87, 3, 1284);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(21, 3, 1067);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(21, 3, 1068);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(21, 3, 1069);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(21, 3, 1070);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(21, 3, 1071);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(21, 3, 1260);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(22, 3, 87);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(22, 3, 88);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(22, 3, 89);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(22, 3, 90);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(22, 3, 91);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(22, 3, 1212);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(24, 3, 97);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(24, 3, 98);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(24, 3, 99);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(24, 3, 100);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(24, 3, 101);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(24, 3, 1214);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(54, 3, 397);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(54, 3, 398);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(54, 3, 399);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(54, 3, 400);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(54, 3, 401);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(54, 3, 1244);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(59, 3, 407);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(59, 3, 408);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(59, 3, 409);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(59, 3, 410);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(59, 3, 411);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(59, 3, 1246);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(61, 3, 417);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(61, 3, 418);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(61, 3, 419);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(61, 3, 420);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(61, 3, 421);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(61, 3, 1248);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(62, 3, 422);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(62, 3, 423);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(62, 3, 424);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(62, 3, 425);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(62, 3, 426);
INSERT INTO adoptconvergebss.tblaclentry
(classid, roleid, permit)
VALUES(62, 3, 1249);
