#url=jdbc:mysql://143.198.175.154:3306/adoptconvergebss
#url=jdbc:mysql://10.124.0.5:3306/adoptconvergebss
url=jdbc:mysql://localhost:3306/adoptconvergebss
username=root
password=root
driver=com.mysql.jdbc.Driver