#log4j.rootLogger=${LOG_LEVEL:-DEBUG}, file, console
#
#log4j.appender.file=org.apache.log4j.RollingFileAppender
#log4j.appender.file.File=log/adopt-CMS.log
#log4j.appender.file.MaxFileSize=100MB
#log4j.appender.file.MaxBackupIndex=10
#log4j.appender.file.layout=org.apache.log4j.PatternLayout
#log4j.appender.file.layout.ConversionPattern={"level":"%p", "user":"%X{userName}", "trace-id":"%X{traceId}", "span-id":"%X{spanId}", "type":"%X{type}","timestamp":"%d{ISO8601}", "module":"Adopt-Customer-Management", "thread":"%t", "sub-module":"%F", "line":"%L", "message":"%m"}%n
#
#log4j.appender.console=org.apache.log4j.ConsoleAppender
#log4j.appender.console.layout=org.apache.log4j.PatternLayout
#log4j.appender.console.layout.ConversionPattern={"level":"%p", "user":"%X{userName}", "trace-id":"%X{traceId}", "span-id":"%X{spanId}", "type":"%X{type}","timestamp":"%d{ISO8601}", "module":"Adopt-Customer-Management", "thread":"%t", "sub-module":"%F", "line":"%L", "message":"%m"}%n
#
#log4j.logger.commonlog=DEBUG, commonlog
#log4j.additivity.commonlog=false
#log4j.appender.commonlog=org.apache.log4j.RollingFileAppender
#log4j.appender.commonlog.File=AdoptWifiServer.log
#log4j.appender.commonlog.MaxFileSize=100MB
#log4j.appender.commonlog.MaxBackupIndex=10
#log4j.appender.commonlog.layout=org.apache.log4j.PatternLayout
#log4j.appender.commonlog.layout.ConversionPattern= {"level":"%p", "user":"%X{userName}", "trace-id":"%X{traceId:-}", "span-id":"%X{spanId:-}", "type":"%X{type}","timestamp":"%d{ISO8601}", "module":"Adopt-wifi", "thread":"%t", "sub-module":"%F", "line":"%L", "message":"%m"}%n
#
## Logger for CustomersService
#log4j.logger.com.adopt.apigw.service.common.CustomersService=DEBUG, customersServiceAppender
#log4j.additivity.com.adopt.apigw.service.common.CustomersService=false
#
#
## Logger for TaxService
#log4j.logger.com.adopt.apigw.service.postpaid.TaxService=INFO, customersServiceAppender
#log4j.additivity.com.adopt.apigw.service.postpaid.TaxService=false
#
#
## Logger for TaxService
#log4j.logger.com.adopt.apigw.modules.Teams.service.HierarchyService=INFO, customersServiceAppender
#log4j.additivity.com.adopt.apigw.modules.Teams.service.HierarchyService=false
#
#
## Appender for CustomersService logs with the new pattern
#log4j.appender.customersServiceAppender=org.apache.log4j.RollingFileAppender
#log4j.appender.customersServiceAppender.File=logs/customersService.log
#log4j.appender.customersServiceAppender.MaxFileSize=100MB
#log4j.appender.customersServiceAppender.MaxBackupIndex=10
#log4j.appender.customersServiceAppender.layout=org.apache.log4j.PatternLayout
#log4j.appender.customersServiceAppender.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c{1}.%L - %X{correlationId} %X{userId} - %m%n
#
#
