api.canonical.name.payu=com.adopt.apigw.modules.payments.util.PayuPGHelper
api.canonical.name.ccavenue=com.adopt.apigw.modules.payments.util.CCAvenueHelper
#Payu Money Config
payu.db.id=1
payu.classname=com.adopt.apigw.modules.payments.util.PayuPGHelper
payu.merchant.id=oqOHPi
payu.merchant.salt=8FyKopAH
payu.auth.header=LWFKzU2A7FknkOhPCGqsZHvv6qgE5fc6rb0SjigqufY=
payu.surl.partner=http://143.110.248.5:20080/api/v1/order/process
payu.furl.partner=http://143.110.248.5:20080/api/v1/order/process
payu.surl.customer=http://143.110.248.5:20080/api/portal/v1/subscriber/order/process
payu.furl.customer=http://143.110.248.5:20080/api/portal/v1/subscriber/order/process
payu.submiturl=https://secure.payu.in/_payment
payu.clientredirecturl=http://143.110.248.5
payu.clientredirecturlforcustportal=http://143.110.248.5:20082
#CCAvenue PG Config
ccavenue.db.id=2
ccavenue.classname=com.adopt.apigw.modules.payments.util.CCAvenueHelper
ccavenue.merchant.id=244061
ccavenue.access_code=AVZS16IH22CA60SZAC
ccavenue.enc_key=825010E15788899713D6313E0A388D53
ccavenue.submiturl=https://secure.ccavenue.com/transaction/transaction.do?command=initiateTransaction
ccavenue.redirect_url=http://143.110.248.5:20080/api/v1/order/process
ccavenue.cancel_url=http://143.110.248.5:20080/api/v1/order/process
#Payment gateway
pguser.roleName=PGUser
pguser.roleId=9
pguser.staffId=9
pguser.staffName=PGUser






