DONT USE THI MERGE WITH MAIN


/* 
CREATE TABLE TBLMMVNO
  (
    MVNOID           serial,
    NAME             VARCHAR(64) NOT NULL,
    SUFFIX           VARCHAR(16),
    DESCRIPTION      VARCHAR(255),
    EMAIL            VARCHAR(255),
    PHONE            VARCHAR(255),
    ADDRESS          VARCHAR(255),
    STATUS           CHAR(1),
    LOGOFILE         VARCHAR(255),
    MVNOHEADER       VARCHAR(255),
    MVNOFOOTER       VARCHAR(255),
    CREATEDATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LASTMODIFIEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MVNOID)
  );

  CREATE TABLE TBLMTAX
  (
    TAXID                 serial,
    NAME                  VARCHAR(64) NOT NULL,
    DESCRIPTION           VARCHAR(255),
    TAXTYPE               VARCHAR(8),
    STATUS                CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATEDATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATEDBYSTAFFID      NUMERIC(20),
    LASTMODIFIEDBYSTAFFID NUMERIC(20),
    LASTMODIFIEDDATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MVNOID                bigint UNSIGNED,
    PRIMARY KEY (TAXID),
    FOREIGN KEY (MVNOID) REFERENCES TBLMMVNO (MVNOID)
  );
  
CREATE TABLE TBLMTIERTAX
  (
    TIERTAXID serial,
    NAME      VARCHAR(64) NOT NULL,
    TAXGROUP  VARCHAR(10),
    RATE      NUMERIC(10,2),
    TAXID     bigint UNSIGNED,
    PRIMARY KEY (TIERTAXID),	
    FOREIGN KEY (TAXID) REFERENCES TBLMTAX (TAXID)
  );
  
CREATE TABLE TBLMSLABTAX
  (
    SLABTAXID serial,
    NAME      VARCHAR(64) NOT NULL,
    RANGEFROM NUMERIC(16,4),
    RANGEUPTO NUMERIC(16,4),
    RATE      NUMERIC(10,2),
    TAXID     bigint UNSIGNED,
    PRIMARY KEY (SLABTAXID),
    FOREIGN KEY (TAXID) REFERENCES TBLMTAX (TAXID)
  );
  
CREATE TABLE TBLMPOSTPAIDPLAN
  (
    POSTPAIDPLANID        serial,
    NAME                  VARCHAR(64) NOT NULL,
    DISPLAYNAME           VARCHAR(128),
    PLANCODE              VARCHAR(8) NOT NULL,
    DESCRIPTION           VARCHAR(255),
    PLANCATEGORY          VARCHAR(32),
    MAXALLOWEDCHILD       NUMERIC(8),
    STARTDATE             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENDDATE               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    QUOTA                 NUMERIC(14,4),
    QUOTAUNIT             VARCHAR(8),
    UPLOADQOS             VARCHAR(128), 
    DOWNLOADQOS           VARCHAR(128), 
    STATUS                CHAR(1) DEFAULT 'Y' NOT NULL,
    PLANSTATUS            VARCHAR(32) DEFAULT 'INACTIVE',
    CHILDQUOTA            NUMERIC(14,4), 
    CHILDQUOTAUNIT        VARCHAR(8),
    SLICE                 NUMERIC(14,4),
    SLICEUNIT             VARCHAR(8),
    PARAM1                VARCHAR(4000),
    PARAM2                VARCHAR(4000),
    PARAM3                VARCHAR(4000),
    ATTACHEDTOALLHOTSPOT  VARCHAR(8) DEFAULT 'false',
    CREATEDATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATEDBYSTAFFID      NUMERIC(20),
    LASTMODIFIEDBYSTAFFID NUMERIC(20),
    LASTMODIFIEDDATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MVNOID                bigint UNSIGNED,
	TAXID                 bigint UNSIGNED,
    PRIMARY KEY (POSTPAIDPLANID),
    FOREIGN KEY (MVNOID) REFERENCES TBLMMVNO (MVNOID),
    FOREIGN KEY (TAXID) REFERENCES TBLMTAX (TAXID)
  );
  
  CREATE TABLE TBLMPOSTPAIDPLANCHARGEREL
  (
	POSTPAIDPLANCHARGERELID serial,
	NAME VARCHAR(64),
	DESCRIPTION VARCHAR(255),
	PRICE NUMERIC(16,4),
	CHARGETYPE VARCHAR(32),
	BILLINGCYCLE NUMERIC(2,0),
	CREATEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	POSTPAIDPLANID bigint UNSIGNED,
	PRIMARY KEY (POSTPAIDPLANCHARGERELID),
	FOREIGN KEY (POSTPAIDPLANID) REFERENCES TBLMPOSTPAIDPLAN (POSTPAIDPLANID)
  );

 INSERT INTO TBLMMVNO (NAME,SUFFIX,DESCRIPTION,EMAIL,PHONE,ADDRESS,STATUS,LOGOFILE,MVNOHEADER,MVNOFOOTER,CREATEDATE,LASTMODIFIEDDATE) value('Default','DEF','Default MVNO','admin@default.com','1234567890','INDIA','1',null,null,null,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP())

 
 CREATE TABLE TBLMDISCOUNT
  (
    DISCOUNTID  serial,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS      CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATEDBYSTAFFID      NUMERIC(20),
    LASTMODIFIEDBYSTAFFID NUMERIC(20),
    LASTMODIFIEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MVNOID bigint UNSIGNED,
    PRIMARY KEY (DISCOUNTID),
    FOREIGN KEY (MVNOID) REFERENCES TBLMMVNO (MVNOID)
  );
  
CREATE TABLE TBLMDISCOUNTFIELDMAPPING
  (
    DISCOUNTFIELDMAPPINGID serial,
    VALIDFROM              TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    VALIDUPTO              TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    DISCOUNTTYPE           VARCHAR(16),
    DISCOUNT               NUMERIC(16,4),
    DISCOUNTID             bigint UNSIGNED,
    PRIMARY KEY (DISCOUNTFIELDMAPPINGID),
    FOREIGN KEY (DISCOUNTID) REFERENCES TBLMDISCOUNT (DISCOUNTID)
  );
  
CREATE TABLE TBLMDISCOUNTPOSTPAIDPLANREL
  (
    DISCOUNTPLANRELID serial,
  	DISCOUNTID     bigint UNSIGNED,
    POSTPAIDPLANID bigint UNSIGNED,
    PRIMARY KEY (DISCOUNTPLANRELID),
    FOREIGN KEY (DISCOUNTID) REFERENCES TBLMDISCOUNT (DISCOUNTID),
    FOREIGN KEY (POSTPAIDPLANID) REFERENCES TBLMPOSTPAIDPLAN (POSTPAIDPLANID)
  );
  
*/