package com.adopt.apigw.soap.Dto;

;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.12.03 at 01:46:41 PM IST
//

import com.adopt.apigw.soap.Dto.ServiceSubscription;

import javax.xml.bind.annotation.*;
import java.util.List;


@XmlRootElement(name = "SubscriberAccount")
@XmlAccessorType(XmlAccessType.FIELD)
public class SubscriberAccount {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Activated")
    protected String activated;
    @XmlElement(name = "Password")
    protected String password;
    @XmlElement(name = "LocationLock")
    protected String locationLock;
    @XmlElement(name = "ServiceSubscriptions")
    private List<ServiceSubscription> serviceSubscriptions;


    public String getName() {
        return name;
    }
    public void setName(String value) {
        this.name = value;
    }


    public String getActivated() {
        return activated;
    }
    public void setActivated(String value) {
        this.activated = value;
    }


    public String getPassword() {
        return password;
    }
    public void setPassword(String value) {
        this.password = value;
    }


    public String getLocationLock() {
        return locationLock;
    }
    public void setLocationLock(String value) {
        this.locationLock = value;
    }


    public List<ServiceSubscription> getServiceSubscriptions() {
        return serviceSubscriptions;
    }

    public void setServiceSubscriptions(List<ServiceSubscription> serviceSubscriptions) {
        this.serviceSubscriptions = serviceSubscriptions;
    }
}

