package com.adopt.apigw.modules.PaymentConfig.model;

public class PaymentGatewayConfigurationConstant {

    public interface PAYMENT_GATEWAY_LIST{
        String PAYTM = "PAYTM";

        String FLUTTERWAVE = "FLUTTERWAVE";

        String ERRICSON = "ERRICSON";

        String RAZORPAY = "RAZORPAY";

        String BUDPAY = "BUDPAY";

        String PHONEPE ="PHONEPE";

        String MOMOPE = "MOMOPE";

        String MOMO_PAY = "MoMo Pay";

        String MOMO_PAY_USSD_PUSH = "MoMo Pay Ussd Push";

        String AIRTEL_USSD_PUSH = "Airtel Ussd Push";


    }

    public interface PAYTM{

        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
        String REDIRECT_CWSC_URL = "REDIRECT_CWSC_URL";
        String REDIRECT_CAPTIVE_URL = "REDIRECT_CAPTIVE_URL";
        String PAYTM_CALLBACK_URL = "PAYTM_CALLBACK_URL";
        String PAYTM_CMS_ADDRESS = "PAYTM_CMS_ADDRESS";
        String PAYTM_CHANNEL_ID = "PAYTM_CHANNEL_ID";
        String PAYTM_INDUSTRY_TYPE_ID = "PAYTM_INDUSTRY_TYPE_ID";
        String PAYTM_MERCHENT_ID = "PAYTM_MERCHENT_ID";
        String PAYTM_WEBSITE = "PAYTM_WEBSITE";
        String PAYTM_MERCHANT_KEY = "PAYTM_MERCHANT_KEY";
        String PAYTM_PAYMENT_URL = "PAYTM_PAYMENT_URL";
        String PAYTM_PAYMENT_LINK_URL = "PAYTM_PAYMENT_LINK_URL";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String MVNO_NAME = "MVNO_NAME";

        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";

        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";

    }

    public interface FLUTTER_WAVE{

        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
        String CWSC_REDIRECT_URL= "CWSC_REDIRECT_URL";
        String CAPTIVE_REDIRECT_URL = "CAPTIVE_REDIRECT_URL";
        String FLUTTERWAVE_PUBLIC_KEY = "FLUTTERWAVE_PUBLIC_KEY";

        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String FLUTTERWAVE_SECRET_KEY = "FLUTTERWAVE_SECRET_KEY";

        String FLUTTERWAVE_CURRENCY = "FLUTTERWAVE_CURRENCY";

        String MVNO_NAME = "MVNO_NAME";

        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";

        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";


    }

    public interface MTN_ERRICSON{
        String PAYMENT_GATEWAY_NAME = "PAYMENT_GATEWAY_NAME";
    }

    public interface RAZORPAY{

        String CWSC_REDIRECT_URL= "CWSC_REDIRECT_URL";
        String CAPTIVE_REDIRECT_URL = "CAPTIVE_REDIRECT_URL";
        String RAZORPAY_CURRENCY = "RAZORPAY_CURRENCY";
        String RAZORPAY_KEY_ID = "RAZORPAY_KEY_ID";
        String RAZORPAY_CALLBACK_URL = "RAZORPAY_CALLBACK_URL";
        String RAZORPAY_SECRET_KEY = "RAZORPAY_SECRET_KEY";
        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";
        String STAFFUSER_USERNAME = "STAFFUSER_USERNAME";
        String STAFFUSER_PASSWORD = "STAFFUSER_PASSWORD";
    }


    public interface BUDPAY{

        String BUDPAY_SECRET_KEY = "BUDPAY_SECRET_KEY";
        String BUDPAY_PUBLIC_KEY = "BUDPAY_PUBLIC_KEY";

        String BUDPAY_CALLBACK_URL = "BUDPAY_CALLBACK_URL";

        String BUDPAY_REQUEST_URL = "BUDPAY_REQUEST_URL";

        String BUDPAY_REDIRECT_URL = "BUDPAY_REDIRECT_URL";

        String REDIRECT_TIME_IN_SECONDS = "REDIRECT_TIME_IN_SECONDS";

        String BUDPAY_CALLBACK_CWSC_BUY_URL = "BUDPAY_CALLBACK_CWSC_BUY_URL";

        String BUDPAY_VERIFY_STATUS_URL = "BUDPAY_VERIFY_STATUS_URL";
    }

    public interface PHONEPE{

        String PHONEPE_MERCHANT_ID = "PHONEPE_MERCHANT_ID";

        String PHONEPE_MERCHANT_USERID = "PHONEPE_MERCHANT_USERID";

        String PHONEPE_CALLBACK_URL = "PHONEPE_CALLBACK_URL";

        String PHONEPE_SALT_INDEX = "PHONEPE_SALT_INDEX";

        String PHONEPE_SALT_KEY = "PHONEPE_SALT_KEY";
        String PHONEPE_REDIRECT_URL = "PHONEPE_REDIRECT_URL";

        String PHONPE_REDIRECT_MODE = "PHONPE_REDIRECT_MODE";

        String PHONPE_PAYMENT_INSTRUMENT_TYPE = "PHONPE_PAYMENT_INSTRUMENT_TYPE";

        String PHONPE_GATEWAY_URL = "PHONPE_GATEWAY_URL";

    }


}
